CREATE DATABASE '127.0.0.1/gds_db:C:\DADOS\MICRODATA.GDB'   USER 'SYSDBA'
   PAGE_SIZE 4096
   DEFAULT CHARACTER SET WIN1251;
/* Definition for the `PRODUTOS_ID_GEN` generator :  */

CREATE GENERATOR PRODUTOS_ID_GEN;

/* Definition for the `TBPEDIDOITEM_ID_GEN` generator :  */

CREATE GENERATOR TBPEDIDOITEM_ID_GEN;

/* Definition for the `TBPEDIDO_ID_GEN` generator :  */

CREATE GENERATOR TBPEDIDO_ID_GEN;

/* Definition for the `TBPRODUTO_ID_GEN` generator :  */

CREATE GENERATOR TBPRODUTO_ID_GEN;

SET GENERATOR TBPRODUTO_ID_GEN TO 5;
CREATE TABLE TBPEDIDO (
  ID INTEGER NOT NULL,
  CLIENTE VARCHAR(60) CHARACTER SET WIN1251 NOT NULL COLLATE WIN1251,
  VRTOTALPEDIDO NUMERIC(15, 2) NOT NULL,
  DATAPEDIDO DATE NOT NULL,
  DATADIGITACAO DATE NOT NULL,
  OBSERVACAO VARCHAR(200) CHARACTER SET WIN1251 COLLATE WIN1251);


ALTER TABLE TBPEDIDO ADD PRIMARY KEY (ID);

CREATE TABLE TBPEDIDOITEM (
  ID INTEGER NOT NULL,
  PEDIDOID INTEGER NOT NULL,
  PRODUTOID INTEGER NOT NULL,
  QUANTIDADE INTEGER NOT NULL,
  VRUNITARIO NUMERIC(15, 2) NOT NULL,
  DESCONTOITEM NUMERIC(15, 2),
  VRTOTALITEM NUMERIC(15, 2) NOT NULL,
  OBSERVACAO VARCHAR(200) CHARACTER SET WIN1251 COLLATE WIN1251);


ALTER TABLE TBPEDIDOITEM ADD CONSTRAINT UQ_TBPEDIDOITEM UNIQUE (PEDIDOID,PRODUTOID);

ALTER TABLE TBPEDIDOITEM ADD PRIMARY KEY (ID);

CREATE TABLE TBPRODUTO (
  ID INTEGER NOT NULL,
  DESCRICAO VARCHAR(100) CHARACTER SET WIN1251 NOT NULL COLLATE WIN1251);


ALTER TABLE TBPRODUTO ADD PRIMARY KEY (ID);
/* Data for the `TBPRODUTO` table  (Records 1 - 5) */

INSERT INTO TBPRODUTO
VALUES (1, 'SAPATO');

INSERT INTO TBPRODUTO
VALUES (2, 'TENIS');

INSERT INTO TBPRODUTO
VALUES (3, 'CHINELO');

INSERT INTO TBPRODUTO
VALUES (4, 'BLUSA');

INSERT INTO TBPRODUTO
VALUES (5, 'JEANS');

COMMIT WORK;

/* Definition for the `FK_TBPEDIDOITEM` foreign key :  */

ALTER TABLE TBPEDIDOITEM ADD CONSTRAINT FK_TBPEDIDOITEM FOREIGN KEY (PEDIDOID) REFERENCES TBPEDIDO(ID);

/* Definition for the `FK_TBPEDIDOITEM1` foreign key :  */

ALTER TABLE TBPEDIDOITEM ADD CONSTRAINT FK_TBPEDIDOITEM1 FOREIGN KEY (PRODUTOID) REFERENCES TBPRODUTO(ID);
/* Definition for the `BI_TBPEDIDOITEM_ID` trigger :  */

SET TERM ^ ;

CREATE TRIGGER BI_TBPEDIDOITEM_ID FOR TBPEDIDOITEM
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
      NEW.ID = GEN_ID(TBPEDIDOITEM_ID_GEN, 1);
END^

SET TERM ; ^

/* Definition for the `BI_TBPEDIDO_ID` trigger :  */

SET TERM ^ ;

CREATE TRIGGER BI_TBPEDIDO_ID FOR TBPEDIDO
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
      NEW.ID = GEN_ID(TBPEDIDO_ID_GEN, 1);
END^

SET TERM ; ^

/* Definition for the `BI_TBPRODUTO_ID` trigger :  */

SET TERM ^ ;

CREATE TRIGGER BI_TBPRODUTO_ID FOR TBPRODUTO
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
      NEW.ID = GEN_ID(TBPRODUTO_ID_GEN, 1);
END^

SET TERM ; ^
/* Privilegies for the `TBPEDIDO` :  */

GRANT SELECT, INSERT, DELETE, REFERENCES, UPDATE ON TBPEDIDO TO SYSDBA WITH GRANT OPTION;


/* Privilegies for the `TBPEDIDOITEM` :  */

GRANT SELECT, INSERT, DELETE, REFERENCES, UPDATE ON TBPEDIDOITEM TO SYSDBA WITH GRANT OPTION;


/* Privilegies for the `TBPRODUTO` :  */

GRANT SELECT, INSERT, DELETE, REFERENCES, UPDATE ON TBPRODUTO TO SYSDBA WITH GRANT OPTION;

